import { Workflow, WorkflowNode, WorkflowEdge } from '../components/types';

export function generateMoonBitCode(workflow: Workflow): string {
  const { name, description, nodes, edges } = workflow;
  
  const lines: string[] = [
    `// MoonFlow Workflow: ${name}`,
    `// Generated by MoonFlow Studio`,
    `// ${new Date().toISOString()}`,
    '',
    'package moonflow_generated',
    '',
    'pub fn main {',
    `  println("Starting workflow: ${name}")`,
    '',
  ];

  lines.push('  // Initialize workflow nodes');
  nodes.forEach((node, index) => {
    lines.push(`  let ${toVariableName(node.label)}_${index} = init_node("${node.type}", "${node.label}")`);
  });

  lines.push('');
  lines.push('  // Define workflow connections');
  edges.forEach((edge) => {
    const sourceNode = nodes.find(n => n.id === edge.source);
    const targetNode = nodes.find(n => n.id === edge.target);
    if (sourceNode && targetNode) {
      const sourceVar = toVariableName(sourceNode.label) + '_' + nodes.indexOf(sourceNode);
      const targetVar = toVariableName(targetNode.label) + '_' + nodes.indexOf(targetNode);
      lines.push(`  connect(${sourceVar}, ${targetVar})`);
    }
  });

  lines.push('');
  lines.push('  // Execute workflow');
  const startNodes = findStartNodes(nodes, edges);
  const endNodes = findEndNodes(nodes, edges);
  
  if (startNodes.length > 0) {
    lines.push('  // Start nodes (triggers)');
    startNodes.forEach((node) => {
      const varName = toVariableName(node.label) + '_' + nodes.indexOf(node);
      lines.push(`  execute(${varName})`);
    });
  }

  lines.push('');
  lines.push('  println("Workflow execution completed")');
  lines.push('}');
  lines.push('');
  lines.push('// Helper functions');
  lines.push('');
  lines.push('fn init_node(component: String, label: String) -> Node {');
  lines.push('  Node::{ component, label }');
  lines.push('}');
  lines.push('');
  lines.push('fn connect(source: Node, target: Node) -> () {');
  lines.push('  // Create edge between nodes');
  lines.push('  println(`Connecting: ${source.label} -> ${target.label}`)');
  lines.push('}');
  lines.push('');
  lines.push('fn execute(node: Node) -> () {');
  lines.push('  // Execute node component');
  lines.push('  println(`Executing: ${node.label} (${node.component})`)');
  lines.push('}');
  lines.push('');
  lines.push('struct Node {');
  lines.push('  component: String');
  lines.push('  label: String');
  lines.push('}');

  return lines.join('\n');
}

function toVariableName(label: string): string {
  return label
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

function findStartNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const targetIds = new Set(edges.map(e => e.target));
  return nodes.filter(node => !targetIds.has(node.id));
}

function findEndNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const sourceIds = new Set(edges.map(e => e.source));
  return nodes.filter(node => !sourceIds.has(node.id));
}

export function validateWorkflow(workflow: Workflow): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!workflow.id) {
    errors.push('Workflow ID is required');
  }

  if (!workflow.name) {
    errors.push('Workflow name is required');
  }

  if (workflow.nodes.length === 0) {
    errors.push('Workflow must have at least one node');
  }

  const startNodes = findStartNodes(workflow.nodes, workflow.edges);
  if (startNodes.length === 0) {
    errors.push('Workflow must have at least one start node (node with no incoming edges)');
  }

  const endNodes = findEndNodes(workflow.nodes, workflow.edges);
  if (endNodes.length === 0) {
    errors.push('Workflow must have at least one end node (node with no outgoing edges)');
  }

  const nodeIds = new Set(workflow.nodes.map(n => n.id));
  workflow.edges.forEach((edge, index) => {
    if (!nodeIds.has(edge.source)) {
      errors.push(`Edge ${index}: source node "${edge.source}" does not exist`);
    }
    if (!nodeIds.has(edge.target)) {
      errors.push(`Edge ${index}: target node "${edge.target}" does not exist`);
    }
  });

  const unreachableNodes = findUnreachableNodes(workflow.nodes, workflow.edges);
  if (unreachableNodes.length > 0) {
    errors.push(`Unreachable nodes detected: ${unreachableNodes.map(n => n.label).join(', ')}`);
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

function findUnreachableNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const startNodes = findStartNodes(nodes, edges);
  const reachable = new Set<string>();
  const queue = [...startNodes];

  while (queue.length > 0) {
    const node = queue.shift()!;
    if (reachable.has(node.id)) continue;
    reachable.add(node.id);

    const outgoing = edges.filter(e => e.source === node.id);
    outgoing.forEach(edge => {
      const targetNode = nodes.find(n => n.id === edge.target);
      if (targetNode && !reachable.has(targetNode.id)) {
        queue.push(targetNode);
      }
    });
  }

  return nodes.filter(n => !reachable.has(n.id));
}
