import { Workflow, WorkflowNode, WorkflowEdge } from '../components/types';

export interface CodeGeneratorOptions {
  asyncExecution?: boolean;
  errorHandling?: boolean;
  logging?: boolean;
  typeAnnotations?: boolean;
}

export function generateMoonBitCode(
  workflow: Workflow,
  options: CodeGeneratorOptions = {}
): string {
  const {
    asyncExecution = true,
    errorHandling = true,
    logging = true,
    typeAnnotations = true,
  } = options;

  const { name, description, nodes, edges } = workflow;
  
  const lines: string[] = [
    `// MoonFlow Workflow: ${name}`,
    `// Generated by MoonFlow Studio v0.1.0`,
    `// ${new Date().toISOString()}`,
    '',
    'package moonflow_generated',
    '',
  ];

  if (logging) {
    lines.push('import moonflow/core { Logger, LogLevel }');
    lines.push('');
  }

  if (asyncExecution) {
    lines.push('import moonflow/async { AsyncExecutor, Pipeline }');
    lines.push('');
  }

  lines.push('pub fn main {');
  lines.push(`  println("Starting workflow: ${name}")`);
  
  if (logging) {
    lines.push('  Logger.info("Initializing workflow execution")');
  }

  lines.push('');
  lines.push('  // Initialize workflow context');
  lines.push('  let ctx = WorkflowContext::()');
  lines.push('');

  lines.push('  // Initialize and configure nodes');
  nodes.forEach((node, index) => {
    const varName = toVariableName(node.label) + '_' + index;
    lines.push(`  let ${varName} = ${generateNodeInit(node, typeAnnotations)}`);
    
    if (node.config && Object.keys(node.config).length > 0) {
      lines.push(`  ${varName}.configure(${generateConfigCode(node)})`);
    }
  });

  lines.push('');
  lines.push('  // Build execution pipeline');
  
  if (asyncExecution) {
    lines.push('  let pipeline = Pipeline::()');
    const sortedNodes = topologicalSort(nodes, edges);
    sortedNodes.forEach(nodeId => {
      const node = nodes.find(n => n.id === nodeId)!;
      const varName = toVariableName(node.label) + '_' + nodes.indexOf(node);
      lines.push(`  pipeline.add(${varName})`);
    });
    lines.push('');
    lines.push('  // Execute pipeline asynchronously');
    lines.push('  let result = pipeline.execute(ctx)');
  } else {
    const startNodes = findStartNodes(nodes, edges);
    startNodes.forEach((node) => {
      const varName = toVariableName(node.label) + '_' + nodes.indexOf(node);
      lines.push(`  execute_node(${varName}, ctx)`);
    });
  }

  lines.push('');
  
  if (errorHandling) {
    lines.push('  // Handle execution results');
    lines.push('  match result {');
    lines.push('    Ok(_) => {');
    if (logging) {
      lines.push('      Logger.info("Workflow completed successfully")');
    }
    lines.push('      println("Workflow execution completed")');
    lines.push('    }');
    lines.push('    Err(e) => {');
    if (logging) {
      lines.push('      Logger.error(`Workflow failed: $\{e.message}`)');
    }
    lines.push('      println(`Error: $\{e.message}`)');
    lines.push('    }');
    lines.push('  }');
  } else {
    if (logging) {
      lines.push('  Logger.info("Workflow execution completed")');
    }
    lines.push('  println("Workflow execution completed")');
  }

  lines.push('}');
  lines.push('');
  lines.push('// Workflow Context');
  lines.push('struct WorkflowContext {');
  lines.push('  state: Map[String, Any]');
  lines.push('  metadata: Map[String, String]');
  lines.push('}');
  lines.push('');
  lines.push('impl WorkflowContext {');
  lines.push('  fn init() -> WorkflowContext {');
  lines.push('    WorkflowContext::{ state: Map::(), metadata: Map::() }');
  lines.push('  }');
  lines.push('');
  lines.push('  fn get(self, key: String) -> Option[Any] {');
  lines.push('    self.state.get(key)');
  lines.push('  }');
  lines.push('');
  lines.push('  fn set(self, key: String, value: Any) -> () {');
  lines.push('    self.state.set(key, value)');
  lines.push('  }');
  lines.push('');
  lines.push('  fn clear(self) -> () {');
  lines.push('    self.state.clear()');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('// Node type definitions');
  lines.push(generateNodeTypeDefinitions());
  lines.push('');
  lines.push('// Node factory functions');
  lines.push(generateNodeFactoryFunctions());
  lines.push('');
  lines.push('// Execution functions');
  lines.push(generateExecutionFunctions(errorHandling, logging));
  lines.push('');
  lines.push('// Helper functions');
  lines.push(generateHelperFunctions(edges, nodes));

  return lines.join('\n');
}

function generateNodeInit(node: WorkflowNode, typeAnnotations: boolean): string {
  const componentType = getComponentType(node.type);
  const typeHint = typeAnnotations ? `: ${componentType}` : '';
  return `init_${node.type}_node("${node.label}"${typeHint})`;
}

function getComponentType(type: string): string {
  const typeMap: Record<string, string> = {
    http: 'HttpNode',
    llm: 'LlmNode',
    database: 'DatabaseNode',
    cache: 'CacheNode',
    response: 'ResponseNode',
    transformer: 'TransformerNode',
    websocket: 'WebSocketNode',
    grpc: 'GrpcNode',
    graphql: 'GraphQLNode',
  };
  return typeMap[type] || 'GenericNode';
}

function generateConfigCode(node: WorkflowNode): string {
  if (!node.config) return '{}';
  
  const configPairs = Object.entries(node.config)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join(', ');
  
  return `{ ${configPairs} }`;
}

function generateNodeTypeDefinitions(): string {
  return `// Node types for different components
struct HttpNode {
  label: String
  component: String
  config: HttpConfig
}

struct HttpConfig {
  url: String
  method: String
  headers: Map[String, String]
  timeout: Int
}

struct LlmNode {
  label: String
  component: String
  config: LlmConfig
}

struct LlmConfig {
  model: String
  provider: String
  api_key: String
  system_prompt: String
  user_prompt: String
  temperature: Float
  max_tokens: Int
  base_url: String
}

struct DatabaseNode {
  label: String
  component: String
  config: DatabaseConfig
}

struct DatabaseConfig {
  connection_string: String
  query: String
  operation: String
}

struct CacheNode {
  label: String
  component: String
  config: CacheConfig
}

struct CacheConfig {
  provider: String
  ttl: Int
  key: String
}

struct ResponseNode {
  label: String
  component: String
  config: ResponseConfig
}

struct ResponseConfig {
  status_code: Int
  headers: Map[String, String]
  body: String
}

struct TransformerNode {
  label: String
  component: String
  config: TransformerConfig
}

struct TransformerConfig {
  transform_type: String
  mappings: Map[String, String]
}

// Generic node for custom components
struct GenericNode {
  label: String
  component: String
  config: Map[String, Any]
}

impl GenericNode {
  fn configure(self, config: Map[String, Any]) -> GenericNode {
    GenericNode::{ label: self.label, component: self.component, config }
  }
}`;
}

function generateNodeFactoryFunctions(): string {
  return `// Node factory functions
fn init_http_node(label: String) -> HttpNode {
  HttpNode::{ label, component: "http", config: HttpConfig::{
    url: "",
    method: "GET",
    headers: Map::(),
    timeout: 30000
  }}
}

fn init_llm_node(label: String) -> LlmNode {
  LlmNode::{ label, component: "llm", config: LlmConfig::{
    model: "gpt-4",
    provider: "openai",
    api_key: "",
    system_prompt: "",
    user_prompt: "",
    temperature: 0.7,
    max_tokens: 2048,
    base_url: ""
  }}
}

fn init_database_node(label: String) -> DatabaseNode {
  DatabaseNode::{ label, component: "database", config: DatabaseConfig::{
    connection_string: "",
    query: "",
    operation: "select"
  }}
}

fn init_cache_node(label: String) -> CacheNode {
  CacheNode::{ label, component: "cache", config: CacheConfig::{
    provider: "redis",
    ttl: 3600,
    key: ""
  }}
}

fn init_response_node(label: String) -> ResponseNode {
  ResponseNode::{ label, component: "response", config: ResponseConfig::{
    status_code: 200,
    headers: Map::(),
    body: ""
  }}
}

fn init_transformer_node(label: String) -> TransformerNode {
  TransformerNode::{ label, component: "transformer", config: TransformerConfig::{
    transform_type: "map",
    mappings: Map::()
  }}
}

fn init_websocket_node(label: String) -> WebSocketNode {
  WebSocketNode::{ label, component: "websocket", config: WebSocketConfig::{
    url: "",
    protocols: [],
    auto_reconnect: true
  }}
}

fn init_grpc_node(label: String) -> GrpcNode {
  GrpcNode::{ label, component: "grpc", config: GrpcConfig::{
    service: "",
    method: "",
    endpoint: ""
  }}
}

fn init_graphql_node(label: String) -> GraphQLNode {
  GraphQLNode::{ label, component: "graphql", config: GraphQLConfig::{
    endpoint: "",
    query: "",
    variables: Map::()
  }}
}

fn init_generic_node(label: String, component: String) -> GenericNode {
  GenericNode::{ label, component, config: Map::() }
}`;
}

function generateExecutionFunctions(errorHandling: boolean, logging: boolean): string {
  let code = '// Execute a single node\n';
  code += 'fn execute_node(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
  
  if (logging) {
    code += '  Logger.debug(`Executing node: $\{node.label}`)\n';
  }
  
  code += '  // Execute node logic based on component type\n';
  code += '  match node.component {\n';
  code += '    "http" => execute_http(node, ctx),\n';
  code += '    "llm" => execute_llm(node, ctx),\n';
  code += '    "database" => execute_database(node, ctx),\n';
  code += '    "cache" => execute_cache(node, ctx),\n';
  code += '    "response" => execute_response(node, ctx),\n';
  code += '    "websocket" => execute_websocket(node, ctx),\n';
  code += '    "grpc" => execute_grpc(node, ctx),\n';
  code += '    "graphql" => execute_graphql(node, ctx),\n';
  code += '    "transformer" => execute_transformer(node, ctx),\n';
  code += '    _ => execute_generic(node, ctx)\n';
  code += '  }\n';
  
  if (errorHandling) {
    code += '}\n\n';
    code += '// Error handling\n';
    code += 'struct Error {\n';
    code += '  code: Int\n';
    code += '  message: String\n';
    code += '  details: Map[String, String]\n';
    code += '}\n\n';
    code += 'fn execute_http(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing HTTP request: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let url = config.get("url").or("")\n';
    code += '  let method = config.get("method").or("GET")\n';
    code += '  \n';
    code += '  match HttpClient::request(method, url) {\n';
    code += '    Ok(response) => {\n';
    code += '      Logger.info(`HTTP request successful: $\{response.status}`)\n';
    code += '      ctx.set("last_response", response.body)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`HTTP request failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 500, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_llm(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing LLM inference: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let provider = config.get("provider").or("openai")\n';
    code += '  let model = config.get("model").or("gpt-4")\n';
    code += '  let api_key = config.get("api_key").or("")\n';
    code += '  let system_prompt = config.get("system_prompt").or("")\n';
    code += '  let user_prompt = config.get("user_prompt").or("")\n';
    code += '  let temperature = config.get("temperature").or("0.7").to_float()\n';
    code += '  let max_tokens = config.get("max_tokens").or("2048").to_int()\n';
    code += '  let base_url = config.get("base_url").or("")\n';
    code += '  \n';
    code += '  // Resolve user prompt with context variables\n';
    code += '  let input = ctx.get("last_response").or("")\n';
    code += '  let resolved_prompt = replace_variables(user_prompt, input)\n';
    code += '  \n';
    code += '  Logger.info(`LLM request: provider=\{provider}, model=\{model}`)\n';
    code += '  \n';
    code += '  match provider {\n';
    code += '    "openai" => {\n';
    code += '      let client = OpenAIClient::new(api_key, base_url)\n';
    code += '      match client.complete(model, system_prompt, resolved_prompt, temperature, max_tokens) {\n';
    code += '        Ok(result) => {\n';
    code += '          Logger.info(`LLM inference successful`)\n';
    code += '          ctx.set("llm_result", result.content)\n';
    code += '          ctx.set("llm_usage", result.usage)\n';
    code += '          Ok(())\n';
    code += '        }\n';
    code += '        Err(e) => {\n';
    code += '          Logger.error(`OpenAI API failed: $\{e.message}`)\n';
    code += '          Err(Error::{ code: 501, message: e.message, details: Map::() })\n';
    code += '        }\n';
    code += '      }\n';
    code += '    }\n';
    code += '    "claude" => {\n';
    code += '      let client = ClaudeClient::new(api_key)\n';
    code += '      match client.complete(model, system_prompt, resolved_prompt, max_tokens) {\n';
    code += '        Ok(result) => {\n';
    code += '          Logger.info(`Claude API successful`)\n';
    code += '          ctx.set("llm_result", result.content)\n';
    code += '          ctx.set("llm_usage", result.usage)\n';
    code += '          Ok(())\n';
    code += '        }\n';
    code += '        Err(e) => {\n';
    code += '          Logger.error(`Claude API failed: $\{e.message}`)\n';
    code += '          Err(Error::{ code: 501, message: e.message, details: Map::() })\n';
    code += '        }\n';
    code += '      }\n';
    code += '    }\n';
    code += '    "gemini" => {\n';
    code += '      let client = GeminiClient::new(api_key, base_url)\n';
    code += '      match client.complete(model, resolved_prompt, temperature, max_tokens) {\n';
    code += '        Ok(result) => {\n';
    code += '          Logger.info(`Gemini API successful`)\n';
    code += '          ctx.set("llm_result", result.content)\n';
    code += '          ctx.set("llm_usage", result.usage)\n';
    code += '          Ok(())\n';
    code += '        }\n';
    code += '        Err(e) => {\n';
    code += '          Logger.error(`Gemini API failed: $\{e.message}`)\n';
    code += '          Err(Error::{ code: 501, message: e.message, details: Map::() })\n';
    code += '        }\n';
    code += '      }\n';
    code += '    }\n';
    code += '    _ => {\n';
    code += '      Logger.error(`Unsupported LLM provider: \{provider}`)\n';
    code += '      Err(Error::{ code: 501, message: "Unsupported LLM provider: \{provider}", details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_database(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing database query: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let query = config.get("query").or("SELECT 1")\n';
    code += '  \n';
    code += '  match DatabaseClient::execute(query) {\n';
    code += '    Ok(result) => {\n';
    code += '      Logger.info(`Database query successful`)\n';
    code += '      ctx.set("db_result", result)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`Database query failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 502, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_cache(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing cache operation: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let operation = config.get("operation").or("get")\n';
    code += '  let key = config.get("key").or("")\n';
    code += '  \n';
    code += '  match CacheClient::\{ operation, key \}.execute() {\n';
    code += '    Ok(result) => {\n';
    code += '      Logger.info(`Cache operation successful`)\n';
    code += '      ctx.set("cache_result", result)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`Cache operation failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 503, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_response(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Generating response: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let status_code = config.get("status_code").or("200").to_int()\n';
    code += '  let body = ctx.get("llm_result").or(ctx.get("db_result").or(""))\n';
    code += '  \n';
    code += '  let response = HttpResponse::\{\n';
    code += '    status_code,\n';
    code += '    body,\n';
    code += '    headers: Map::()\n';
    code += '  \}\n';
    code += '  \n';
    code += '  Logger.info(`Response generated with status: $\{status_code}`)\n';
    code += '  ctx.set("response", response)\n';
    code += '  Ok(())\n';
    code += '}\n\n';
    code += 'fn execute_websocket(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing WebSocket: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let url = config.get("url").or("")\n';
    code += '  let protocol = config.get("protocol").or("")\n';
    code += '  let auto_reconnect = config.get("auto_reconnect").or("true").to_bool()\n';
    code += '  \n';
    code += '  match WebSocketClient::connect(url, protocol, auto_reconnect) {\n';
    code += '    Ok(ws) => {\n';
    code += '      Logger.info(`WebSocket connected: $\{url}`)\n';
    code += '      let message = ctx.get("last_response").or("")\n';
    code += '      ws.send(message)\n';
    code += '      match ws.receive() {\n';
    code += '        Ok(response) => {\n';
    code += '          Logger.info(`WebSocket message received`)\n';
    code += '          ctx.set("ws_result", response)\n';
    code += '          ws.close()\n';
    code += '          Ok(())\n';
    code += '        }\n';
    code += '        Err(e) => {\n';
    code += '          ws.close()\n';
    code += '          Err(Error::{ code: 504, message: "WebSocket receive failed: $\{e.message}", details: Map::() })\n';
    code += '        }\n';
    code += '      }\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`WebSocket connection failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 504, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_grpc(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing gRPC call: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let service = config.get("service").or("")\n';
    code += '  let method = config.get("method").or("")\n';
    code += '  let endpoint = config.get("endpoint").or("localhost:50051")\n';
    code += '  let request_data = ctx.get("last_response").or("{}")\n';
    code += '  \n';
    code += '  match GrpcClient::call(endpoint, service, method, request_data) {\n';
    code += '    Ok(response) => {\n';
    code += '      Logger.info(`gRPC call successful`)\n';
    code += '      ctx.set("grpc_result", response)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`gRPC call failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 505, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_graphql(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing GraphQL query: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let endpoint = config.get("endpoint").or("")\n';
    code += '  let query = config.get("query").or("")\n';
    code += '  let variables = config.get("variables").or("{}")\n';
    code += '  \n';
    code += '  match GraphQLClient::query(endpoint, query, variables) {\n';
    code += '    Ok(response) => {\n';
    code += '      Logger.info(`GraphQL query successful`)\n';
    code += '      ctx.set("graphql_result", response)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`GraphQL query failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 506, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_transformer(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.info(`Executing data transformation: $\{node.label}`)\n';
    code += '  let config = node.config\n';
    code += '  let transform_type = config.get("transform_type").or("map")\n';
    code += '  let mappings = config.get("mappings").or("{}")\n';
    code += '  let input = ctx.get("last_response").or("{}")\n';
    code += '  \n';
    code += '  let transformer = Transformer::\{\n';
    code += '    transform_type,\n';
    code += '    mappings: Json::parse(mappings),\n';
    code += '  \}\n';
    code += '  \n';
    code += '  match transformer.apply(input) {\n';
    code += '    Ok(result) => {\n';
    code += '      Logger.info(`Transformation successful`)\n';
    code += '      ctx.set("transformed", result)\n';
    code += '      Ok(())\n';
    code += '    }\n';
    code += '    Err(e) => {\n';
    code += '      Logger.error(`Transformation failed: $\{e.message}`)\n';
    code += '      Err(Error::{ code: 507, message: e.message, details: Map::() })\n';
    code += '    }\n';
    code += '  }\n';
    code += '}\n\n';
    code += 'fn execute_generic(node: GenericNode, ctx: WorkflowContext) -> Result[Unit, Error] {\n';
    code += '  Logger.warn(`Unknown component type: $\{node.component}`)\n';
    code += '  Ok(())\n';
    code += '}\n';
  } else {
    code += '  Ok(())\n';
    code += '}\n';
  }
  
  return code;
}

function generateHelperFunctions(edges: WorkflowEdge[], nodes: WorkflowNode[]): string {
  let code = `// Helper function to convert labels to valid variable names
fn to_variable_name(label: String) -> String {
  label.to_lower().replace(" ", "_")
}

// Find start nodes (nodes with no incoming edges)
fn find_start_nodes() -> Array[String] {
  let targets = Array::()
`;

  edges.forEach(edge => {
    code += `  targets.push("${edge.target}")\n`;
  });

  code += `  let starts = Array::()\n`;
  nodes.forEach(node => {
    code += `  if not(targets.contains("${node.id}")) {\n`;
    code += `    starts.push("${node.id}")\n`;
    code += `  }\n`;
  });

  code += `  starts
}

// Find end nodes (nodes with no outgoing edges)
fn find_end_nodes() -> Array[String] {
  let sources = Array::()
`;

  edges.forEach(edge => {
    code += `  sources.push("${edge.source}")\n`;
  });

  code += `  let ends = Array::()\n`;
  nodes.forEach(node => {
    code += `  if not(sources.contains("${node.id}")) {\n`;
    code += `    ends.push("${node.id}")\n`;
    code += `  }\n`;
  });

  code += `  ends
}

// Get outgoing edges from a node
fn get_outgoing_edges(node_id: String) -> Array[Edge] {
  let edges = Array::()
`;

  edges.forEach(edge => {
    code += `  edges.push(Edge::{ source: "${edge.source}", target: "${edge.target}" })\n`;
  });

  code += `  edges.filter(fn(e: Edge) => e.source == node_id)
}

// Get incoming edges to a node
fn get_incoming_edges(node_id: String) -> Array[Edge] {
  let edges = Array::()
`;

  edges.forEach(edge => {
    code += `  edges.push(Edge::{ source: "${edge.source}", target: "${edge.target}" })\n`;
  });

  code += `edges.filter(fn(e: Edge) => e.target == node_id)
}

// Edge structure
struct Edge {
  source: String
  target: String
}

// Replace context variables in prompt templates
// Variables are in format {{variable_name}} and are replaced with actual values
fn replace_variables(template: String, context: String) -> String {
  let result = template
  // Replace {{last_response}} or {{last_output}} with context
  result = result.replace("{{last_response}}", context)
  result = result.replace("{{last_output}}", context)
  result = result.replace("{{input}}", context)
  // Replace timestamp placeholder
  let timestamp = to_string(timestamp_now())
  result = result.replace("{{timestamp}}", timestamp)
  // Replace other common variables
  result
}

// Get current timestamp
fn timestamp_now() -> Int64 {
  // This would use system time in real implementation
  0
}

// Validate LLM configuration
fn validate_llm_config(config: LlmConfig) -> Result[Unit, String] {
  if config.api_key == "" {
    return Err("API key is required for LLM node")
  }
  if config.model == "" {
    return Err("Model name is required for LLM node")
  }
  if config.temperature < 0.0 || config.temperature > 2.0 {
    return Err("Temperature must be between 0.0 and 2.0")
  }
  if config.max_tokens < 1 || config.max_tokens > 100000 {
    return Err("Max tokens must be between 1 and 100000")
  }
  Ok(())
}`;

  return code;
}

function toVariableName(label: string): string {
  return label
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

function findStartNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const targetIds = new Set(edges.map(e => e.target));
  return nodes.filter(node => !targetIds.has(node.id));
}

function findEndNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const sourceIds = new Set(edges.map(e => e.source));
  return nodes.filter(node => !sourceIds.has(node.id));
}

function topologicalSort(nodes: WorkflowNode[], edges: WorkflowEdge[]): string[] {
  const inDegree = new Map<string, number>();
  const adjacency = new Map<string, string[]>();
  
  nodes.forEach(node => {
    inDegree.set(node.id, 0);
    adjacency.set(node.id, []);
  });
  
  edges.forEach(edge => {
    inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
    adjacency.get(edge.source)?.push(edge.target);
  });
  
  const queue: string[] = [];
  inDegree.forEach((degree, nodeId) => {
    if (degree === 0) queue.push(nodeId);
  });
  
  const result: string[] = [];
  while (queue.length > 0) {
    const nodeId = queue.shift()!;
    result.push(nodeId);
    
    adjacency.get(nodeId)?.forEach(neighbor => {
      const newDegree = (inDegree.get(neighbor) || 0) - 1;
      inDegree.set(neighbor, newDegree);
      if (newDegree === 0) queue.push(neighbor);
    });
  }
  
  return result;
}

export function validateWorkflow(workflow: Workflow): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!workflow.id) {
    errors.push('Workflow ID is required');
  }

  if (!workflow.name) {
    errors.push('Workflow name is required');
  }

  if (workflow.nodes.length === 0) {
    errors.push('Workflow must have at least one node');
  }

  const startNodes = findStartNodes(workflow.nodes, workflow.edges);
  if (startNodes.length === 0) {
    errors.push('Workflow must have at least one start node (node with no incoming edges)');
  }

  const endNodes = findEndNodes(workflow.nodes, workflow.edges);
  if (endNodes.length === 0) {
    errors.push('Workflow must have at least one end node (node with no outgoing edges)');
  }

  const nodeIds = new Set(workflow.nodes.map(n => n.id));
  workflow.edges.forEach((edge, index) => {
    if (!nodeIds.has(edge.source)) {
      errors.push(`Edge ${index}: source node "${edge.source}" does not exist`);
    }
    if (!nodeIds.has(edge.target)) {
      errors.push(`Edge ${index}: target node "${edge.target}" does not exist`);
    }
  });

  const unreachableNodes = findUnreachableNodes(workflow.nodes, workflow.edges);
  if (unreachableNodes.length > 0) {
    errors.push(`Unreachable nodes detected: ${unreachableNodes.map(n => n.label).join(', ')}`);
  }

  const hasCycle = detectCycle(workflow.nodes, workflow.edges);
  if (hasCycle) {
    errors.push('Workflow contains a cycle, which is not allowed in DAG');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

function findUnreachableNodes(nodes: WorkflowNode[], edges: WorkflowEdge[]): WorkflowNode[] {
  const startNodes = findStartNodes(nodes, edges);
  
  if (startNodes.length === 0) return nodes;
  
  const mainStartNode = startNodes[0];
  const reachable = new Set<string>();
  const queue = [mainStartNode];

  while (queue.length > 0) {
    const node = queue.shift()!;
    if (reachable.has(node.id)) continue;
    reachable.add(node.id);

    const outgoing = edges.filter(e => e.source === node.id);
    outgoing.forEach(edge => {
      const targetNode = nodes.find(n => n.id === edge.target);
      if (targetNode && !reachable.has(targetNode.id)) {
        queue.push(targetNode);
      }
    });
  }

  return nodes.filter(n => !reachable.has(n.id));
}

function detectCycle(nodes: WorkflowNode[], edges: WorkflowEdge[]): boolean {
  const visited = new Set<string>();
  const recStack = new Set<string>();
  
  const adjacency = new Map<string, string[]>();
  nodes.forEach(node => adjacency.set(node.id, []));
  edges.forEach(edge => {
    adjacency.get(edge.source)?.push(edge.target);
  });

  function dfs(nodeId: string): boolean {
    visited.add(nodeId);
    recStack.add(nodeId);

    const neighbors = adjacency.get(nodeId) || [];
    for (const neighbor of neighbors) {
      if (!visited.has(neighbor)) {
        if (dfs(neighbor)) return true;
      } else if (recStack.has(neighbor)) {
        return true;
      }
    }

    recStack.delete(nodeId);
    return false;
  }

  for (const node of nodes) {
    if (!visited.has(node.id)) {
      if (dfs(node.id)) return true;
    }
  }

  return false;
}

export function generateWorkflowDocumentation(workflow: Workflow): string {
  let doc = `# ${workflow.name}\n`;
  doc += `${'='.repeat(workflow.name.length)}\n\n`;
  
  if (workflow.description) {
    doc += `## Description\n\n${workflow.description}\n\n`;
  }
  
  doc += `## Workflow Information\n\n`;
  doc += `- **ID**: ${workflow.id}\n`;
  doc += `- **Nodes**: ${workflow.nodes.length}\n`;
  doc += `- **Edges**: ${workflow.edges.length}\n`;
  doc += `- **Generated**: ${new Date().toISOString()}\n\n`;
  
  doc += `## Nodes\n\n`;
  workflow.nodes.forEach((node, index) => {
    doc += `### ${index + 1}. ${node.label}\n\n`;
    doc += `- **ID**: \`${node.id}\`\n`;
    doc += `- **Type**: \`${node.type}\`\n`;
    doc += `- **Position**: (${node.position.x}, ${node.position.y})\n`;
    
    if (node.description) {
      doc += `- **Description**: ${node.description}\n`;
    }
    
    if (node.config && Object.keys(node.config).length > 0) {
      doc += `- **Configuration**:\n`;
      doc += '  ```json\n';
      doc += `  ${JSON.stringify(node.config, null, 2).split('\n').join('\n  ')}\n`;
      doc += '  ```\n';
    }
    
    doc += '\n';
  });
  
  doc += `## Connections\n\n`;
  workflow.edges.forEach((edge, index) => {
    const sourceNode = workflow.nodes.find(n => n.id === edge.source);
    const targetNode = workflow.nodes.find(n => n.id === edge.target);
    doc += `${index + 1}. \`${sourceNode?.label || edge.source}\` → \`${targetNode?.label || edge.target}\`\n`;
  });
  doc += '\n';
  
  doc += `## Execution Order\n\n`;
  const sortedNodes = topologicalSort(workflow.nodes, workflow.edges);
  sortedNodes.forEach((nodeId, index) => {
    const node = workflow.nodes.find(n => n.id === nodeId);
    doc += `${index + 1}. ${node?.label || nodeId}\n`;
  });
  
  return doc;
}
